/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Add: typeof import('./src/components/widgets/Add.vue')['default']
    Card: typeof import('./src/components/widgets/Card.vue')['default']
    Countdown: typeof import('./src/components/widgets/Countdown.vue')['default']
    Date: typeof import('./src/components/Date.vue')['default']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    Search: typeof import('./src/components/Search.vue')['default']
    Trending: typeof import('./src/components/widgets/Trending.vue')['default']
    Website: typeof import('./src/components/widgets/Website.vue')['default']
    WidgetDialog: typeof import('./src/components/WidgetDialog.vue')['default']
    Widgets: typeof import('./src/components/Widgets.vue')['default']
    WidgetsList: typeof import('./src/components/widgets/WidgetsList.vue')['default']
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
  }
}
